--- 
title: "Data analysis using R for Psychology and Social Science"
author: "Alexander (Sasha) Pastukhov"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "Material and exercises for 'Applied data analysis for psychology using the open-source software R' seminar."
---

```{r, setup, include=FALSE}
rmarkdown::find_pandoc(dir = "c:/Program Files/Pandoc", cache=FALSE)
Sys.setenv(lang = "en_US")
```

# Introduction {-}

This book will (try to) teach you how to perform typical data analysis tasks: reading data, transforming and cleaning it up so you can visualize it and perform a statistical analysis of your choice. It covers most topics that you need to get you started but it cannot cover them all. One advantage of R is a sheer size of its ecosystem with new incredible libraries appearing very much on a daily basis. Covering them all is beyond the scope of any book, so instead I will concentrate on (trying to) building a solid understanding of things that you need to extend your R knowledge. Because of that some early chapters (e.g., on [vectors](#vectors), [tables](#tables), or [functions](##functions)) might feel boring and too technical making you wonder why didn't we start with some exciting and useful analysis, working our way down to finer details. I have tried that^[As a matter of fact, this was my approach when learning R.] but, unfortunately, philosophy of R is about have many almost identical ways of achieving the same end. If you do not learn these finer details, you waste time wondering why seemingly the same code works in one case but fails in mysterious ways in the other one^[Talking from a personal experience here.]. Therefore, please bear with me and struggle through vectors (which are everywhere), oddities and inconsistencies of subsetting, and learning how to write a function before you even started to use them properly. I can only promise that, from my personal experience, this is definitely worth the effort.

An important note: this book will _not_ teach you statistics or machine learning. I will mention some widely used packages and functions for performing statistical analysis but I will not go into the details of how they work or how to interpret their output. If you know (enough of) statistics, you will have little trouble understanding how to work with these packages and functions. If you do not, no amount of reading of manuals will make it clearer.


## Why R? {-}
There are many software tools that allow you preprocess, plot, and analyze your data. Some cost money (SPSS, Matlab), some are free  just like R (Python, Julia). Moreover, you can replicate all analysis that we will perform using Python in combination with [Jupyter notebooks](https://jupyter.org/) (for reproducible analysis), [Pandas](https://pandas.pydata.org/) (for Excel-style table), and [statmodels](https://www.statsmodels.org/stable/index.html) (for statistical analysis). R is hardly perfect. For example, its subsetting system is confusing and appears to follow "convenience over safety" approach that does not sit particularly well with me. However, R in combination with piping and  [Tidyverse](https://www.tidyverse.org/) family of packages makes it incredibly easy to write simple, powerful and expressive code, which is very easy to understand (a huge plus, as you will discover). I will run circles around myself trying to replicate the same analysis in Python or Matlab. In addition, R is loved by mathematicians and statisticians, so it tends to have implementations for all cutting edge methods (my impression is that even Python is lagging behind it in that respect).

## Why Tidyverse {-}
The material is heavily skewed towards using [Tidyverse](https://www.tidyverse.org/) family of packages. It looks different enough from base R to the point that one might call it a "dialect" of R^[R is extremely flexible, making it possible to redefine its own syntax.]. Learning Tidyverse means that you have twice as many things to learn: I will always introduce both base R and Tidyverse version. [Tidyverse](https://www.tidyverse.org/) is the main reason I use R (rather than Python or Julia) as it makes data analysis a breeze and makes your life so much easier. This is why I want you to learn its ways. At the same time, there is plenty of useful code that uses base R, so you need to know and understand it as well.

As a matter of fact, R is so rich and flexible that there many dialects and, therefore, plenty of opinion differences ^[Just ask about "base R vs. Tidyverse" on Twitter and see the thread set itself on fire]. For example, [data.table](https://github.com/Rdatatable/data.table) package re-implements the same functionality as base R and Tidyverse in very compact way. I does not fit my style but it might be something that feels natural to you. There are also other packages to handle things like layout out your figures or working with summary tables that might suit you better. Point is, these material barely scratches the surfaces in terms of tools and approaches that you can use. View it as a starting point for your exploration not the complete map.

Another thing to keep in mind is that Tidyverse is under very active development. This means that parts of this material could be outdated by the time you read it. E.g., _dplyr_ [do()](https://dplyr.tidyverse.org/reference/do.html) verb was superseded by an overpowered [summarise()](https://dplyr.tidyverse.org/reference/summarise.html) function, a warning generated by [readr](https://readr.tidyverse.org/) package was adapted for humans but now require an extra step to be used for column specification, etc. None of the changes are breaking and deprecation process is deliberately slow (e.g., [do()](https://dplyr.tidyverse.org/reference/do.html) still works), so even when outdated the code in the book should still work for quite some time. However, you should keep in mind that things _might_ have changed, so it is a good idea to check an official manual from time to time.

## About the seminar {-}
This is a material for _Applied data analysis for psychology using the open-source software R_ seminar as taught at [Institute of Psychology](https://www.uni-bamberg.de/psychologie/) at University of Bamberg. Each chapter covers a single seminar, introducing necessary ideas and is accompanied by a notebook with exercises, which you need to complete and submit. To pass the seminar, you will need to complete all assignments. You do not need to complete or provide correct solutions for _all_ the exercises to pass the course and information on how the points for exercises will be converted to an actual grade (if you need one) or "pass" will be available during the seminar.

The material assumes no foreknowledge of R or programming in general from a reader. Its purpose is to gradually build up your knowledge and introduce to a typical analysis pipeline. It is based on a data that is typical for the field (repeated measures, appearance, accuracy and response time measurements, Likert scale reports, etc.) and you are welcome to suggest your own data set for analysis. Even if you already performed the analysis using some other program, it would still be insightful to compare the different ways and, perhaps, you might gain a new insight. Plus, it is more engaging to work on your data.

Remember that throughout the seminar you can and should(!) always ask me whenever something is unclear, you do not understand a concept or logic behind certain code, or you simply got stuck. Do not hesitate to write me in the team or (better) directly to me in the chat (in the latter case, the notifications are harder miss and we don't spam others with our conversation).

## Thinking like a computer {-}
In some exercises your will not be writing code but reading and understanding it. Your job in this case is "to think like a computer". Your advantage is that computers are very dumb, so instructions for them must be written in a very simple, clear, and unambiguous way. This means that, with practice, reading code is easy for a human (well, reading a well-written code is easy, you will eventually encounter "spaghetti-code" which is easier to rewrite from scratch than to understand). In each case, you simply go through the code line-by-line, doing all computations by hand and writing down values stored in the variables (if there are too many to keep track of). Once you go through the code in this manner, it should be completely transparent for you. No mysteries should remain, you should have no doubts or uncertainty about any(!) line. Moreover, you then can run the code and check that the values you are getting from computer match yours. Any difference means you made a mistake and code is working differently from how you think it does. In any case, **if you not 100% sure about any line of code, ask me, so we can go through it together!**

In a sense, this is the most important programming skill. It is impossible to learn how to write, if you cannot read the code first! Moreover, when programming you will probably spend more time reading the code and making sure that it works correctly than writing the new code. Thus, use this opportunity to practice and never use the code that you do not understand completely. Thus, there is nothing wrong in using [stackoverflow](https://stackoverflow.com/) but **never** use the code you do not understand (do not blindly copy-paste)!

## About the material {-}
The material is **free to use** and is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivatives V4.0 International License](https://creativecommons.org/licenses/by-nc-nd/4.0/).
